#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from geometry_msgs.msg import PoseStamped
from nav_msgs.msg import OccupancyGrid
from std_msgs.msg import String

class IsaacNavigationNode(Node):
    def __init__(self):
        super().__init__('isaac_navigation_node')
        self.goal_publisher = self.create_publisher(PoseStamped, 'goal_pose', 10)
        self.map_subscription = self.create_subscription(
            OccupancyGrid,
            'map', # Subscribing to the map generated by SLAM
            self.map_callback,
            10
        )
        self.cmd_vel_publisher = self.create_publisher(String, 'cmd_vel', 10) # Placeholder for cmd_vel
        self.get_logger().info("Isaac Navigation Node Started. Waiting for map and navigation commands...")
        self.current_map = None

    def map_callback(self, msg):
        self.current_map = msg
        self.get_logger().info("Received map data.")
        # In a real scenario, the navigation stack would use this map for path planning

    def send_goal(self, x, y, yaw):
        goal_pose = PoseStamped()
        goal_pose.header.frame_id = 'map'
        goal_pose.header.stamp = self.get_clock().now().to_msg()
        goal_pose.pose.position.x = float(x)
        goal_pose.pose.position.y = float(y)
        goal_pose.pose.orientation.z = float(yaw) # Simple yaw, needs proper quaternion conversion
        self.goal_publisher.publish(goal_pose)
        self.get_logger().info(f"Sending navigation goal: x={x}, y={y}, yaw={yaw}")

        # Simulate robot movement
        self.get_logger().info("Robot is navigating (placeholder for actual movement)...")
        # For demonstration, you might publish simple cmd_vel messages or wait for a result

    def timer_callback(self):
        # Example: send a fixed goal if a map is available
        if self.current_map:
            self.send_goal(1.0, 0.5, 0.0) # Example goal
            self.get_logger().info("Navigation goal sent automatically for demonstration.")
            # Only send once for this placeholder
            self.timer.cancel()


def main(args=None):
    rclpy.init(args=args)
    isaac_navigation_node = IsaacNavigationNode()
    isaac_navigation_node.timer = isaac_navigation_node.create_timer(5.0, isaac_navigation_node.timer_callback) # Send goal after 5 seconds
    rclpy.spin(isaac_navigation_node)
    isaac_navigation_node.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()
