import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  bookSidebar: [
    'intro',
    'setup-guide',
    {
      type: 'category',
      label: 'Module 1: Fundamentals',
      items: [
        {type: 'autogenerated', dirName: 'module-1-ros'},
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Perception and Navigation',
      items: [
        {type: 'autogenerated', dirName: 'module-2-simulation'},
      ],
    },
    {
        type: 'category',
        label: 'Module 3: Vision-Language-Action Systems',
        items: [
          {type: 'autogenerated', dirName: 'module-3-nvidia-isaac'},
        ],
    },
    {
        type: 'category',
        label: 'Module 4: Advanced Topics',
        items: [
            {type: 'autogenerated', dirName: 'module-4-advanced-integration'},
        ],
    },
    'glossary'
  ],
};

export default sidebars;
