import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  bookSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: Fundamentals',
      items: [
        {type: 'autogenerated', dirName: 'module1'},
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Perception and Navigation',
      items: [
        {type: 'autogenerated', dirName: 'module2'},
      ],
    },
    {
        type: 'category',
        label: 'Module 3: Vision-Language-Action Systems',
        items: [
          {type: 'autogenerated', dirName: 'module3'},
        ],
    },
    {
        type: 'category',
        label: 'Module 4: Advanced Topics',
        items: [
            {type: 'autogenerated', dirName: 'module4'},
        ],
    }
  ],
};

export default sidebars;
